import type { BlockSchema } from "@/types/blocks/builder.types";

const messengerPlatformOptions = [
  { value: "telegram", label: "تلگرام" },
  { value: "whatsapp", label: "واتساپ" },
  { value: "instagram", label: "اینستاگرام" },
  { value: "eitaa", label: "ایتا" },
  { value: "soroush", label: "سروش" },
  { value: "rubika", label: "روبیکا" },
  { value: "bale", label: "بله" },
  { value: "igap", label: "آی‌گپ" },
  { value: "youtube", label: "یوتیوب" },
  { value: "x", label: "ایکس" },
  { value: "linkedin", label: "لینکدین" },
  { value: "signal", label: "سیگنال" },
  { value: "messenger", label: "مسنجر" },
  { value: "discord", label: "دیسکورد" },
] as const;

export const messengerLinksSchema: BlockSchema = {
  type: "messengerLinks",
  label: "پیام‌رسان‌ها",
  description:
    "لینک شبکه‌ها و پیام‌رسان‌ها مثل تلگرام، واتساپ، اینستاگرام، ایتا، سروش، روبیکا و موارد دیگر.",
  contentFields: [
    { key: "title", label: "عنوان", type: "text" },
    { key: "description", label: "توضیحات", type: "textarea" },

    { key: "telegramLabel", label: "لیبل تلگرام", type: "text" },
    { key: "telegramUrl", label: "شناسه تلگرام", type: "text", linkPreset: "telegram" },
    { key: "whatsappLabel", label: "لیبل واتساپ", type: "text" },
    { key: "whatsappUrl", label: "شماره واتساپ با کد کشور", type: "text", linkPreset: "whatsapp" },
    { key: "instagramLabel", label: "لیبل اینستاگرام", type: "text" },
    { key: "instagramUrl", label: "شناسه اینستاگرام", type: "text", linkPreset: "instagram" },
    { key: "eitaaLabel", label: "لیبل ایتا", type: "text" },
    { key: "eitaaUrl", label: "شناسه ایتا", type: "text", linkPreset: "eitaa" },
    { key: "soroushLabel", label: "لیبل سروش", type: "text" },
    { key: "soroushUrl", label: "شناسه سروش", type: "text", linkPreset: "soroush" },
    { key: "rubikaLabel", label: "لیبل روبیکا", type: "text" },
    { key: "rubikaUrl", label: "شناسه روبیکا", type: "text", linkPreset: "rubika" },
    { key: "baleLabel", label: "لیبل بله", type: "text" },
    { key: "baleUrl", label: "شناسه بله", type: "text", linkPreset: "bale" },
    { key: "igapLabel", label: "لیبل آی‌گپ", type: "text" },
    { key: "igapUrl", label: "شناسه آی‌گپ", type: "text", linkPreset: "igap" },
    { key: "signalLabel", label: "لیبل سیگنال", type: "text" },
    { key: "signalUrl", label: "شماره سیگنال", type: "text", linkPreset: "signal" },
    { key: "messengerLabel", label: "لیبل مسنجر", type: "text" },
    { key: "messengerUrl", label: "شناسه مسنجر", type: "text", linkPreset: "messenger" },
    { key: "discordLabel", label: "لیبل دیسکورد", type: "text" },
    { key: "discordUrl", label: "کد دعوت دیسکورد", type: "text", linkPreset: "discord" },
    { key: "xLabel", label: "لیبل ایکس", type: "text" },
    { key: "xUrl", label: "شناسه ایکس", type: "text", linkPreset: "x" },
    { key: "youtubeLabel", label: "لیبل یوتیوب", type: "text" },
    { key: "youtubeUrl", label: "شناسه یوتیوب", type: "text", linkPreset: "youtube" },
    { key: "linkedinLabel", label: "لیبل لینکدین", type: "text" },
    { key: "linkedinUrl", label: "شناسه لینکدین", type: "text", linkPreset: "linkedin" },

    {
      key: "messengerItems",
      label: "پیام‌رسان‌های اضافه",
      type: "repeater",
      itemLabel: "لینک",
      addLabel: "افزودن پیام‌رسان",
      fields: [
        {
          key: "platform",
          label: "نوع پیام‌رسان",
          type: "select",
          defaultValue: "telegram",
          options: messengerPlatformOptions,
        },
        {
          key: "identifier",
          label: "شناسه",
          type: "text",
          linkPresetFromField: "platform",
        },
        { key: "label", label: "لیبل دکمه", type: "text" },
        { key: "enabled", label: "نمایش", type: "boolean", defaultValue: true },
        { key: "brandColor", label: "رنگ برند", type: "color" },
        { key: "backgroundColor", label: "رنگ دکمه", type: "color" },
        { key: "textColor", label: "رنگ متن", type: "color" },
      ],
    },

    { key: "showTitle", label: "نمایش عنوان", type: "boolean" },
    { key: "showDescription", label: "نمایش توضیحات", type: "boolean" },
    { key: "showLabels", label: "نمایش نام پیام‌رسان‌ها", type: "boolean" },

    { key: "showTelegram", label: "نمایش تلگرام", type: "boolean" },
    { key: "showWhatsapp", label: "نمایش واتساپ", type: "boolean" },
    { key: "showInstagram", label: "نمایش اینستاگرام", type: "boolean" },
    { key: "showEitaa", label: "نمایش ایتا", type: "boolean" },
    { key: "showSoroush", label: "نمایش سروش", type: "boolean" },
    { key: "showRubika", label: "نمایش روبیکا", type: "boolean" },
    { key: "showBale", label: "نمایش بله", type: "boolean" },
    { key: "showIgap", label: "نمایش آی‌گپ", type: "boolean" },
    { key: "showSignal", label: "نمایش سیگنال", type: "boolean" },
    { key: "showMessenger", label: "نمایش مسنجر", type: "boolean" },
    { key: "showDiscord", label: "نمایش دیسکورد", type: "boolean" },
    { key: "showX", label: "نمایش ایکس", type: "boolean" },
    { key: "showYoutube", label: "نمایش یوتیوب", type: "boolean" },
    { key: "showLinkedin", label: "نمایش لینکدین", type: "boolean" },

    { key: "openInNewTab", label: "باز شدن در تب جدید", type: "boolean" },
  ],
  elements: {
    container: {
      label: "کادر اصلی",
      allowedStyleKeys: [
        "backgroundColor",
        "borderRadius",
        "borderColor",
        "borderWidth",
        "gridColumns",
        "animation",
      ],
    },
    title: {
      label: "عنوان",
      allowedStyleKeys: ["color", "fontSize", "animation"],
    },
    description: {
      label: "توضیحات",
      allowedStyleKeys: ["color", "fontSize"],
    },
    messengerButton: {
      label: "دکمه پیام‌رسان",
      allowedStyleKeys: [
        "color",
        "backgroundColor",
        "fontSize",
        "borderRadius",
        "borderColor",
        "borderWidth",
        "animation",
      ],
    },
    icon: {
      label: "آیکون",
      allowedStyleKeys: [
        "color",
        "backgroundColor",
        "fontSize",
        "borderRadius",
        "borderColor",
        "borderWidth",
        "animation",
      ],
    },
    label: {
      label: "عنوان پیام‌رسان",
      allowedStyleKeys: ["color", "fontSize"],
    },
  },
};
