import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/global/navbar";
import { estedad } from "@/next-persian-fonts/estedad";
import SmartLandingFooter from "@/components/global/footer";
import { Toaster } from "@/components/ui/CustomToast";
import DynamicIsland from "@/components/ui/DynamicIsland";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${estedad.className}   h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Toaster position="top-right" maxToasts={5}  />
        <Navbar />
        {children}
        <DynamicIsland />
        <SmartLandingFooter />
      </body>
    </html>
  );
}
